[ansible]
skip =
    2.16

[testenv:ruff]
skip_install = true
commands =
    uv run ruff format .

[testenv:yamllint]
skip_install = true
commands =
    uv run yamllint -c .yamllint .

[testenv:flake8]
skip_install = true
commands =
    uv run flake8 --config flake8.ini

[testenv]
commands_pre =
    integration: uv pip install 'molecule' 'molecule-plugins[docker]'
    # Require || true to get past issue:
    # https://github.com/ansible/ansible-dev-environment/issues/349
    integration: bash -c "ade install --requirement extensions/molecule/requirements.yml --no-seed --im none || true"
    integration: bash -c "ade install --no-seed --im none . || true"
