---
ansible:
  playbooks:
    create: ../resources/create_agent.yml
    destroy: ../resources/destroy_agent.yml

scenario:
  test_sequence:
    - create
    - prepare
    - converge
    - cleanup
    - destroy
