---
driver:
  name: docker
dependency:
  name: galaxy
  options:
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/../requirements.yml"
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    expose:
      - 45876
    networks:
      - name: molecule_beszel
scenario:
  name: agent_token
