---
- name: Destroy | Common Tasks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy | Stop and remove container
      community.docker.docker_container:
        name: instance
        state: absent
        auto_remove: true

    - name: Destroy | Stop Beszel Hub Docker Compose Stack
      community.docker.docker_compose_v2:
        project_src: ../
        remove_volumes: true
        state: absent

    - name: Destroy | Remove dynamic inventory file
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        state: absent
