---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Converge | Register a Beszel system
      community.beszel.system:
        url: http://localhost:8090
        username: molecule@example.com
        password: molecule
        name: instance1
        host: instance1
        users:
          - molecule@example.com
        state: present

    - name: Converge | Register a Beszel system using the current user
      community.beszel.system:
        url: http://localhost:8090
        username: molecule@example.com
        password: molecule
        name: instance2
        host: instance2
        port: 45880
        state: present

    - name: Converge | Update an existing Beszel system (change port)
      register: register_system_resp
      community.beszel.system:
        url: http://localhost:8090
        username: molecule@example.com
        password: molecule
        name: instance2
        host: instance2
        port: 45881
        state: present

    - name: Converge | Assert that the Beszel system has been updated
      ansible.builtin.assert:
        that: register_system_resp.system.port == "45881"
        fail_msg: Beszel system has not been updated.

    - name: Converge | Unregister a Beszel system (instance1)
      community.beszel.system:
        url: http://localhost:8090
        username: molecule@example.com
        password: molecule
        name: instance1
        state: absent

    - name: Converge | Unregister a Beszel system (instance2)
      community.beszel.system:
        url: http://localhost:8090
        username: molecule@example.com
        password: molecule
        name: instance2
        state: absent
