---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Converge | Register a Beszel system with a list of users
      register: register_system_resp
      community.beszel.system:
        url: http://localhost:8090
        username: molecule@example.com
        password: molecule
        name: instance1
        host: instance1
        users:
          - molecule@example.com
        port: 45878
        state: present

    - name: Converge | Assert registered Beszel system instance1
      ansible.builtin.assert:
        that:
          - register_system_resp.system.name == "instance1"
          - register_system_resp.system.host == "instance1"
          - register_system_resp.system.port == "45878"
        fail_msg: Beszel system instance1 has not been registered correctly.
