---
- name: Create | Common Create Tasks
  ansible.builtin.import_playbook: ../common/create.yml

- name: Create | Get Beszel Public Key
  ansible.builtin.import_playbook: ../common/beszel_public_key.yml

- name: Create | agent_default
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create | Add container to molecule_inventory
      vars:
        inventory_partial_yaml: |
          all:
            children:
              molecule:
                vars:
                  agent_public_key: "{{ beszel_hub_public_key_resp.json.key }}"
                hosts:
                  "{{ item.name }}":
                    ansible_connection: community.docker.docker
      ansible.builtin.set_fact:
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create | Dump molecule_inventory
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_yaml }}
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Create | Force inventory refresh
      ansible.builtin.meta: refresh_inventory
