---
- name: Create
  hosts: localhost
  gather_facts: false
  vars:
    ci: false
    molecule_inventory:
      all:
        hosts: {}
        children:
          molecule: {}
  tasks:
    - name: Ensure Docker Compose plugin is installed
      when: ci | bool
      block:
        - name: Create | Update apt
          ansible.builtin.apt:
            update_cache: true
            cache_valid_time: 3600

        - name: Create | Ensure Docker Compose plugin is installed
          ansible.builtin.package:
            name: docker-compose-plugin
            state: present

    - name: Create | Start Beszel Hub Docker Compose Stack
      community.docker.docker_compose_v2:
        project_src: ../
        state: present

    - name: Create | Create the initial Beszel Hub user
      ansible.builtin.uri:
        url: http://localhost:8090/api/beszel/create-user
        method: POST
        body:
          email: molecule@example.com
          password: molecule
        body_format: json

    - name: Create | Get Beszel Hub PocketBase API token
      register: beszel_hub_api_token_resp
      ansible.builtin.uri:
        # https://github.com/vaphes/pocketbase/blob/master/pocketbase/services/admin_service.py#L75
        url: http://localhost:8090/api/collections/_superusers/auth-with-password
        method: POST
        headers:
          Authorization: ""
        body:
          identity: molecule@example.com
          password: molecule
        body_format: json

    - name: Create | Get Beszel Hub user IDs
      register: beszel_hub_user_resp
      ansible.builtin.uri:
        url: http://localhost:8090/api/collections/users/records
        method: GET
        headers:
          Authorization: "{{ beszel_hub_api_token_resp.json.token }}"

    - name: Create | Set beszel_hub_user_id
      ansible.builtin.set_fact:
        beszel_hub_user_id: "{{ beszel_hub_user_resp.json | community.general.json_query('items[0].id') }}" # noqa jinja[invalid]

    - name: Create | Get Beszel Public Key
      register: beszel_hub_public_key_resp
      ansible.builtin.uri:
        url: "http://localhost:8090/api/beszel/getkey"
        method: GET
        headers:
          Authorization: "{{ beszel_hub_api_token_resp.json.token }}"

    - name: Create | Create container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: "{{ item.command }}"
        tmpfs: "{{ item.tmpfs }}"
        volumes: "{{ item.volumes }}"
        cgroupns_mode: "{{ item.cgroupns_mode }}"
        privileged: "{{ item.privileged }}"
        networks: "{{ item.networks }}"
        expose: "{{ item.expose }}"
        state: started
      register: result
      loop: "{{ molecule_yml.platforms }}"

    - name: Create | Fail if container is not running
      when: >
        item.container.State.ExitCode != 0 or
        not item.container.State.Running
      ansible.builtin.fail:
        msg: "{{ item.container.Name }} failed to start."
      loop: "{{ result.results }}"

    - name: Create | Add container to molecule_inventory
      vars:
        inventory_partial_yaml: |
          all:
            children:
              molecule:
                vars:
                  agent_public_key: "{{ beszel_hub_public_key_resp.json.key }}"
                  beszel_hub_api_token: "{{ beszel_hub_api_token_resp.json.token }}"
                  beszel_hub_user_id: "{{ beszel_hub_user_id }}"
                hosts:
                  "{{ item.name }}":
                    ansible_connection: community.docker.docker
      ansible.builtin.set_fact:
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create | Dump molecule_inventory
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_yaml }}
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Create | Force inventory refresh
      ansible.builtin.meta: refresh_inventory

    - name: Create | Fail if molecule group is missing
      run_once: true # noqa: run-once[task]
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}
